//
//  ChatMessage.swift
//  NeuraL
//
//  Phase 2 — Conversation Data Models
//
//  This file defines the core data types for representing a chat conversation:
//  - ChatMessage: A single message in a conversation with role, content, and metadata
//  - MessageRole: The role of the message sender (system, user, assistant)
//  - MessageTokenInfo: Token counting metadata for context window management
//  - Conversation: A complete conversation with metadata and token tracking
//
//  Design decisions:
//  - ChatMessage is a value type (struct) for safe concurrent access
//  - Token counts are tracked per-message for granular context eviction
//  - The assistant's streaming state is separate from the finalized message
//  - Messages are never mutated after finalization (append-only log)
//

import Foundation

// MARK: - Phase 6: Supporting Types

/// A record of a function call made by the assistant (Phase 6.2).
struct FunctionCallRecord: Sendable, Identifiable, Codable {
    let id: UUID
    let toolName: String
    let parameters: String // JSON-encoded
    let result: String?
    let isSuccess: Bool
    let durationSeconds: Double
}

/// A citation from RAG sources (Phase 6.3).
struct RAGSourceCitation: Sendable, Identifiable, Codable {
    let id: UUID
    let documentName: String
    let chunkIndex: Int
    let similarity: Float
    let snippet: String
}

// MARK: - Message Role

/// The role of a message sender in the conversation.
///
/// This maps directly to the roles used in chat templates:
/// - system: The system prompt that sets model behavior
/// - user: Human input to the model
/// - assistant: Model-generated response
enum MessageRole: String, Sendable, Codable, CaseIterable, CustomStringConvertible {
    case system
    case user
    case assistant

    var description: String { rawValue }

    /// Whether this role is "evictable" during context window management.
    /// System messages are NEVER evicted; user/assistant messages may be.
    var isEvictable: Bool {
        switch self {
        case .system:    return false
        case .user:      return true
        case .assistant: return true
        }
    }
}

// MARK: - Token Information

/// Token counting metadata for a message, used by the context window manager.
///
/// Token counts are tracked at two levels:
/// 1. Prompt tokens: The number of tokens this message contributes to the
///    formatted prompt (including role tags, special tokens, and formatting).
/// 2. Generation tokens: For assistant messages, the number of tokens
///    generated by the model (not including the prompt portion).
struct MessageTokenInfo: Sendable, Codable {
    /// Number of tokens in this message when formatted with the chat template.
    /// This includes role tags, special tokens, and the message content itself.
    /// For assistant messages, this includes only the "prompt" portion (the
    /// assistant header tag), not the generated tokens.
    let promptTokenCount: Int

    /// For assistant messages only: the number of tokens generated by the model.
    /// Zero for system and user messages.
    let generationTokenCount: Int

    /// Total tokens this message occupies in the KV cache.
    var totalTokenCount: Int {
        promptTokenCount + generationTokenCount
    }

    /// An estimate based on character count, used before exact tokenization.
    /// English text averages ~4 characters per token; code averages ~3.5.
    static func estimate(from text: String, role: MessageRole) -> MessageTokenInfo {
        let estimatedContentTokens = max(1, Int(Double(text.count) / 3.8))
        // Add overhead for role tags and special tokens (varies by template,
        // but ~4-10 tokens per message is typical for Llama-3/Gemma format)
        let templateOverhead = 8
        let promptTokens = estimatedContentTokens + templateOverhead
        let genTokens = 0  // Unknown until generation completes
        return MessageTokenInfo(
            promptTokenCount: promptTokens,
            generationTokenCount: genTokens
        )
    }

    static let zero = MessageTokenInfo(promptTokenCount: 0, generationTokenCount: 0)
}

// MARK: - Generation Metadata

/// Metadata captured when an assistant message finishes generating.
///
/// This is stored for diagnostics and display in the UI (e.g., showing
/// tokens/sec, generation duration, memory usage).
struct GenerationMetadata: Sendable, Codable {
    /// Total tokens generated in this response.
    let tokensGenerated: Int

    /// Wall-clock time for generation (seconds).
    let durationSeconds: Double

    /// Tokens per second (generation only, not prompt processing).
    var tokensPerSecond: Double {
        guard durationSeconds > 0 else { return 0 }
        return Double(tokensGenerated) / durationSeconds
    }

    /// Prompt processing time (seconds).
    let promptProcessingSeconds: Double

    /// Peak memory usage during generation (bytes).
    let peakMemoryBytes: UInt64

    /// The stop reason: why generation ended.
    let stopReason: StopReason

    /// Why generation stopped.
    enum StopReason: String, Sendable, Codable {
        case endOfGenerationToken  // Model produced an EOG token
        case stopTokenMatched      // A stop sequence was matched
        case maxTokensReached      // Hit the max token limit
        case cancelled             // User cancelled generation
        case error                 // An error occurred
    }

    static let placeholder = GenerationMetadata(
        tokensGenerated: 0,
        durationSeconds: 0,
        promptProcessingSeconds: 0,
        peakMemoryBytes: 0,
        stopReason: .maxTokensReached
    )
}

// MARK: - Chat Message

/// A single message in a conversation.
///
/// Messages are immutable value types once finalized. During streaming,
/// the ChatState maintains a separate `streamingText` buffer; when
/// generation completes, the accumulated text is frozen into a new
/// ChatMessage and appended to the conversation.
///
/// Identity is provided by a UUID, which allows stable SwiftUI identity
/// even when messages are reordered or context is evicted and re-processed.
struct ChatMessage: Sendable, Identifiable, Codable {
    /// Unique identifier for this message.
    let id: UUID

    /// The role of the message sender.
    let role: MessageRole

    /// The text content of the message. For assistant messages, this is the
    /// complete generated text after streaming finishes.
    let content: String

    /// Timestamp when the message was created.
    let timestamp: Date

    /// Token counting information for context window management.
    var tokenInfo: MessageTokenInfo

    /// Generation metadata (only for assistant messages, nil otherwise).
    let generationMetadata: GenerationMetadata?

    /// Reasoning text from <think/> blocks (only for assistant messages).
    /// Models like DeepSeek-R1 output their chain-of-thought in <think/> tags.
    /// This is separated from `content` so the UI can show it in a collapsible
    /// "Thought for Xs" block above the main response.
    let thinkingText: String?

    /// Duration of the thinking/reasoning phase in seconds.
    let thinkingDurationSeconds: Double

    /// Whether this message has been included in the current KV cache.
    /// This flag is used by the context evictor to know which messages
    /// are currently "live" in the model's context.
    var isInKVCache: Bool

    // MARK: - Phase 6: Multimodal & Intelligence Fields

    /// Image attachments for this message (Phase 6.1 Vision).
    /// Only user messages typically have image attachments.
    let imageAttachments: [ImageAttachment]?

    /// Function calls made by the assistant during generation (Phase 6.2 Tool Use).
    /// Only assistant messages may contain function calls.
    let functionCalls: [FunctionCallRecord]?

    /// RAG source citations for this message (Phase 6.3 RAG).
    /// Contains the document sources consulted for this response.
    let ragSources: [RAGSourceCitation]?

    // MARK: - Convenience Initializers

    /// Create a system prompt message.
    static func systemPrompt(_ content: String) -> ChatMessage {
        ChatMessage(
            id: UUID(),
            role: .system,
            content: content,
            timestamp: Date(),
            tokenInfo: .estimate(from: content, role: .system),
            generationMetadata: nil,
            thinkingText: nil,
            thinkingDurationSeconds: 0,
            isInKVCache: false,
            imageAttachments: nil,
            functionCalls: nil,
            ragSources: nil
        )
    }

    /// Create a user message.
    static func userMessage(_ content: String, imageAttachments: [ImageAttachment]? = nil) -> ChatMessage {
        ChatMessage(
            id: UUID(),
            role: .user,
            content: content,
            timestamp: Date(),
            tokenInfo: .estimate(from: content, role: .user),
            generationMetadata: nil,
            thinkingText: nil,
            thinkingDurationSeconds: 0,
            isInKVCache: false,
            imageAttachments: imageAttachments,
            functionCalls: nil,
            ragSources: nil
        )
    }

    /// Create a finalized assistant message after generation completes.
    static func assistantMessage(
        _ content: String,
        tokenInfo: MessageTokenInfo,
        metadata: GenerationMetadata?,
        thinkingText: String? = nil,
        thinkingDurationSeconds: Double = 0,
        functionCalls: [FunctionCallRecord]? = nil,
        ragSources: [RAGSourceCitation]? = nil
    ) -> ChatMessage {
        ChatMessage(
            id: UUID(),
            role: .assistant,
            content: content,
            timestamp: Date(),
            tokenInfo: tokenInfo,
            generationMetadata: metadata,
            thinkingText: thinkingText,
            thinkingDurationSeconds: thinkingDurationSeconds,
            isInKVCache: true,
            imageAttachments: nil,
            functionCalls: functionCalls,
            ragSources: ragSources
        )
    }

    /// Update the token info (e.g., after exact tokenization).
    func withTokenInfo(_ newTokenInfo: MessageTokenInfo) -> ChatMessage {
        ChatMessage(
            id: id,
            role: role,
            content: content,
            timestamp: timestamp,
            tokenInfo: newTokenInfo,
            generationMetadata: generationMetadata,
            thinkingText: thinkingText,
            thinkingDurationSeconds: thinkingDurationSeconds,
            isInKVCache: isInKVCache,
            imageAttachments: imageAttachments,
            functionCalls: functionCalls,
            ragSources: ragSources
        )
    }

    /// Mark this message as present in the KV cache.
    func markInKVCache() -> ChatMessage {
        ChatMessage(
            id: id,
            role: role,
            content: content,
            timestamp: timestamp,
            tokenInfo: tokenInfo,
            generationMetadata: generationMetadata,
            thinkingText: thinkingText,
            thinkingDurationSeconds: thinkingDurationSeconds,
            isInKVCache: true,
            imageAttachments: imageAttachments,
            functionCalls: functionCalls,
            ragSources: ragSources
        )
    }
}

// MARK: - Conversation

/// A complete conversation, containing all messages and metadata.
///
/// The Conversation type is the source of truth for the chat history.
/// It supports:
/// - Append-only message addition (no mutation of existing messages)
/// - Token budget tracking for context window management
/// - System prompt identification and preservation
/// - Serialization for persistence (Codable)
///
/// The conversation is passed to the ChatTemplateEngine for formatting
/// and to the SmartContextEvictor for context window management.
struct Conversation: Sendable, Codable {
    /// Unique identifier for this conversation.
    let id: UUID

    /// Title of the conversation (for display in UI).
    /// Auto-generated from the first user message if not set.
    var title: String?

    /// All messages in the conversation, in chronological order.
    /// The first message is typically the system prompt.
    private(set) var messages: [ChatMessage]

    /// Timestamp when the conversation was created.
    let createdAt: Date

    /// Timestamp when the last message was added.
    var lastUpdatedAt: Date

    // MARK: - Computed Properties

    /// The system prompt message, if one exists.
    var systemPrompt: ChatMessage? {
        messages.first { $0.role == .system }
    }

    /// All non-system messages (the conversational turns).
    var conversationalMessages: [ChatMessage] {
        messages.filter { $0.role != .system }
    }

    /// The total number of tokens currently estimated to be in the KV cache.
    /// This is the sum of all messages' tokenInfo.totalTokenCount.
    var totalTokenCount: Int {
        messages.reduce(0) { $0 + $1.tokenInfo.totalTokenCount }
    }

    /// The number of user/assistant message pairs (conversational turns).
    var turnCount: Int {
        conversationalMessages.filter { $0.role == .user }.count
    }

    /// Whether the conversation has any messages.
    var isEmpty: Bool {
        messages.isEmpty
    }

    /// The last message in the conversation.
    var lastMessage: ChatMessage? {
        messages.last
    }

    // MARK: - Initialization

    init(
        id: UUID = UUID(),
        title: String? = nil,
        messages: [ChatMessage] = [],
        createdAt: Date = Date(),
        lastUpdatedAt: Date = Date()
    ) {
        self.id = id
        self.title = title
        self.messages = messages
        self.createdAt = createdAt
        self.lastUpdatedAt = lastUpdatedAt
    }

    /// Create a new conversation with a system prompt.
    init(systemPrompt: String) {
        self.init(
            title: nil,
            messages: [.systemPrompt(systemPrompt)],
            createdAt: Date(),
            lastUpdatedAt: Date()
        )
    }

    // MARK: - Mutation

    /// Append a message to the conversation.
    mutating func append(_ message: ChatMessage) {
        messages.append(message)
        lastUpdatedAt = Date()

        // Auto-generate title from first user message
        if title == nil, message.role == .user {
            let candidate = String(message.content.prefix(60))
            title = candidate
        }
    }

    /// Remove a specific message by ID.
    mutating func removeMessage(id: UUID) {
        messages.removeAll { $0.id == id }
        lastUpdatedAt = Date()
    }

    /// Remove the oldest evictable message pair (user + assistant).
    /// Returns the number of tokens freed by the eviction.
    /// Preserves the system prompt.
    @discardableResult
    mutating func evictOldestTurn() -> Int {
        // Find the first user message
        guard let firstUserIndex = messages.firstIndex(where: { $0.role == .user }) else {
            return 0
        }

        var tokensFreed = messages[firstUserIndex].tokenInfo.totalTokenCount

        // Remove the user message
        messages.remove(at: firstUserIndex)

        // If the next message is an assistant response, remove it too
        // (the index shifted by 1 after removing the user message)
        if firstUserIndex < messages.count && messages[firstUserIndex].role == .assistant {
            tokensFreed += messages[firstUserIndex].tokenInfo.totalTokenCount
            messages.remove(at: firstUserIndex)
        }

        // Mark all remaining messages as needing re-processing
        for i in messages.indices {
            messages[i] = messages[i].withTokenInfo(.zero).markInKVCache() // will be updated on re-process
        }

        lastUpdatedAt = Date()
        return tokensFreed
    }

    /// Update token info for a specific message.
    mutating func updateTokenInfo(for messageId: UUID, tokenInfo: MessageTokenInfo) {
        guard let index = messages.firstIndex(where: { $0.id == messageId }) else { return }
        messages[index] = messages[index].withTokenInfo(tokenInfo)
    }

    /// Mark all messages as not in KV cache (used after context reset).
    mutating func invalidateKVCacheState() {
        for i in messages.indices {
            messages[i].isInKVCache = false
        }
    }

    // MARK: - Context Window Analysis

    /// Analyze which messages should be evicted to fit within a token budget.
    ///
    /// This returns the indices of messages that would be removed, without
    /// actually removing them. The SmartContextEvictor uses this to plan
    /// eviction before executing it.
    ///
    /// - Parameter tokenBudget: Maximum tokens allowed in context.
    /// - Parameter reservedTokens: Tokens to reserve for the upcoming
    ///   generation (typically 256-512).
    /// - Returns: Array of message indices to evict.
    func evictionPlan(tokenBudget: Int, reservedTokens: Int) -> [Int] {
        let effectiveBudget = tokenBudget - reservedTokens
        var currentTotal = totalTokenCount
        var indicesToEvict: [Int] = []

        // Never evict system prompt (index 0 if it's a system message)
        let systemPromptIndices = Set(
            messages.enumerated()
                .filter { $0.element.role == .system }
                .map(\.offset)
        )

        // Find user/assistant pairs to evict, oldest first
        var userMessageIndices = messages.enumerated()
            .filter { $0.element.role == .user && !systemPromptIndices.contains($0.offset) }
            .map(\.offset)

        while currentTotal > effectiveBudget && !userMessageIndices.isEmpty {
            let userIndex = userMessageIndices.removeFirst()
            indicesToEvict.append(userIndex)
            currentTotal -= messages[userIndex].tokenInfo.totalTokenCount

            // Check if the next message is the assistant's response
            let nextIndex = userIndex + 1
            if nextIndex < messages.count && messages[nextIndex].role == .assistant {
                indicesToEvict.append(nextIndex)
                currentTotal -= messages[nextIndex].tokenInfo.totalTokenCount
            }
        }

        return indicesToEvict
    }
}

// MARK: - Conversation Persistence

/// Manages saving and loading conversations to/from the app's Documents directory.
enum ConversationStore {
    private static let storeDirectoryName = "Conversations"

    /// Get the URL for the conversations directory.
    static func storeDirectory() throws -> URL {
        let documentsDir = try FileManager.default.url(
            for: .documentDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: true
        )
        let storeDir = documentsDir.appendingPathComponent(storeDirectoryName)

        if !FileManager.default.fileExists(atPath: storeDir.path) {
            try FileManager.default.createDirectory(
                at: storeDir,
                withIntermediateDirectories: true
            )
        }

        return storeDir
    }

    /// Save a conversation to disk.
    static func save(_ conversation: Conversation) throws {
        let dir = try storeDirectory()
        let fileURL = dir.appendingPathComponent("\(conversation.id.uuidString).json")
        let data = try JSONEncoder().encode(conversation)
        try data.write(to: fileURL, options: .atomic)
    }

    /// Load a conversation from disk.
    static func load(id: UUID) throws -> Conversation {
        let dir = try storeDirectory()
        let fileURL = dir.appendingPathComponent("\(id.uuidString).json")
        let data = try Data(contentsOf: fileURL)
        return try JSONDecoder().decode(Conversation.self, from: data)
    }

    /// List all saved conversation IDs.
    static func listAll() throws -> [UUID] {
        let dir = try storeDirectory()
        let files = try FileManager.default.contentsOfDirectory(
            at: dir,
            includingPropertiesForKeys: nil
        )
        return files.compactMap { url in
            UUID(uuidString: url.deletingPathExtension().lastPathComponent)
        }
    }

    /// Delete a conversation from disk.
    static func delete(id: UUID) throws {
        let dir = try storeDirectory()
        let fileURL = dir.appendingPathComponent("\(id.uuidString).json")
        try FileManager.default.removeItem(at: fileURL)
    }
}
